version: '3'
networks:
  admin:
    driver: bridge
  user:
    driver: bridge

services:

  admin_mysql:
    image: mysql:8
    container_name: admin_mysql
    ports:
      - 33076:3306
    
    networks:
      - admin
    volumes: 
      - ./admin_mysql:/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ali450892
      MYSQL_DATABASE: resturant_admin
      MYSQL_SERVICE_TAGS: dev
      MYSQL_SERVICE_NAME: mysql
    restart: always

  admin_app:

    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 8081:8081
    networks:
      - admin
    volumes:
      - ./admin:/app
    container_name: admin_app
    depends_on:
      - admin_mysql
  
  admin_app2:

    build:
      context: .
      dockerfile: dockerfile1
    ports:
      - 8082:8082
    networks:
      - admin
    volumes:
      - ./admin:/app
    container_name: admin_app2
    depends_on:
      - admin_mysql
      - admin_app
  admin_redis_app:
    image: redis:latest
    container_name: redis_app

    networks:
      - admin
    ports:
      - 6379:6379

    volumes:
      - ./redis:/redis


  user_mysql:
    image: mysql:8
    container_name: user_mysql
    ports:
      - 33077:3306
    
    networks:
      - user
    volumes: 
      - ./user_mysql:/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ali450892
      MYSQL_DATABASE: resturant_user
    
    restart: always

  user_app:

    build:
      context: .
      dockerfile: dockerfile2
    ports:
      - 9081:9081
    networks:
      - user
    volumes:
      - ./user:/app
    container_name: user_app
    depends_on:
      - user_mysql
  
  user_app2:

    build:
      context: .
      dockerfile: dockerfile3
    ports:
      - 9082:9082
    networks:
      - user
    volumes:
      - ./user:/app
    container_name: user_app2
    depends_on:
      - user_mysql
      - user_app
  